version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chatserver-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatserver
    ports:
      - "53306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: chatserver-redis
    restart: always
    ports:
      - "56379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: